### ISSUE TITLE
Selecting "Continue last game" crash when no save exists

### ISSUE THREAD

**Issue by B33J** [patjw/theredprison#4]
(As of the current version in Git)
When no save already exists, when on the main menu and selecting "(b) Continue last game." the game crashes:

```
Traceback (most recent call last):
  File "C:\theredprison\TheRedPrison.py", line 14983, in <module>
    main_menu()
  File "C:\theredprison\TheRedPrison.py", line 14268, in main_menu
    load_game()
  File "C:\theredprison\TheRedPrison.py", line 12987, in load_game
    file = shelve.open('save/savegame', 'r')
  File "C:\Program Files\Python39\lib\shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "C:\Program Files\Python39\lib\shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "C:\Program Files\Python39\lib\dbm\__init__.py", line 85, in open
    raise error[0]("db file doesn't exist; "
dbm.error: db file doesn't exist; use 'c' or 'n' flag to create a new db
```

**Comment by B33J** [comment]
I'll close this now because I think the code was edited for testing, but it still works appropriately with the latest Steam release.
